# Generated by Django 4.2.19 on 2025-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jouteseventpage',
            name='header_title',
            field=models.CharField(blank=True, help_text='Titre personnalisé à afficher dans le header', max_length=150),
        ),
    ]
