# Generated by Django 5.0.10 on 2025-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArtio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='pdf')),
            ],
        ),
    ]
