# Generated by Django 4.2.19 on 2025-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productartio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productartio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue_sete/'),
        ),
        migrations.AlterField(
            model_name='productartio',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
