# Generated by Django 4.2.19 on 2025-03-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productartio_img_alter_productartio_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productartio',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='productartio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue_artio/'),
        ),
    ]
