# Generated by Django 5.0.10 on 2025-01-17 13:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='body',
        ),
        migrations.AddField(
            model_name='footertext',
            name='text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
