# Generated by Django 5.0.10 on 2025-01-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_footertext_body_footertext_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertext',
            old_name='text',
            new_name='body',
        ),
    ]
