# Generated by Django 5.0.10 on 2025-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_text_footertext_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='pinterest_url',
            field=models.URLField(blank=True, verbose_name='Pinterest URL'),
        ),
    ]
