# Generated by Django 5.1.4 on 2024-12-17 10:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_cta',
            field=models.CharField(blank=True, help_text='Contact forms CTA', max_length=255, verbose_name='Contact CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_cta_link',
            field=models.ForeignKey(blank=True, help_text='contact Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
    ]
