# Generated by Django 5.0.10 on 2025-01-15 15:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_contact_cta_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mention_cta',
            field=models.CharField(blank=True, help_text='Mention CTA', max_length=255, verbose_name='Mention CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mention_cta_link',
            field=models.ForeignKey(blank=True, help_text='mention Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='mention CTA link'),
        ),
    ]
