# Generated by Django 5.0.10 on 2025-01-16 10:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mentionpage_homepage_mention_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentionpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
