# Generated by Django 5.0.10 on 2025-01-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mentionpage_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentionPage',
        ),
    ]
