# Generated by Django 5.0.10 on 2025-01-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_mentionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='mention_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mention_cta_link',
        ),
    ]
