# Generated by Django 5.0.10 on 2025-01-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_mention_cta_homepage_mention_cta_link'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mention_cta',
            field=models.CharField(blank=True, help_text='Mention CTA', max_length=255, verbose_name='Mention CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mention_cta_link',
            field=models.ForeignKey(blank=True, help_text='mention Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='mention CTA link'),
        ),
    ]
