# Generated by Django 5.0.10 on 2025-01-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_navigationsettings_footertext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
