# Generated by Django 5.0.10 on 2025-01-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_policy_cta_homepage_policy_cta_link'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='policy_cta_link',
            field=models.ForeignKey(blank=True, help_text='policy Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='policy CTA link'),
        ),
    ]
