# Generated by Django 4.2.19 on 2025-03-12 15:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0013_alter_homepage_policy_cta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='mention_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mention_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='policy_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='policy_cta_link',
        ),
        migrations.CreateModel(
            name='HomePageGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('carousel_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
