# Generated by Django 4.2.19 on 2025-03-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_mention_cta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagegalleryimages',
            old_name='carousel_image',
            new_name='image',
        ),
    ]
