# Generated by Django 4.2.19 on 2025-04-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homepagegalleryimages_image_setoise_part1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesetoise',
            old_name='page_setoise',
            new_name='page',
        ),
    ]
