# Generated by Django 4.2.19 on 2025-04-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_page_setoise_homepagesetoise_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesetoise',
            old_name='image_part1',
            new_name='image',
        ),
    ]
