# Generated by Django 4.2.19 on 2025-06-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0021_homepagesetoise3'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='events_cta',
            field=models.CharField(blank=True, help_text='Events forms CTA', max_length=255, verbose_name='Events CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_cta_link',
            field=models.ForeignKey(blank=True, help_text='Events Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Events CTA link'),
        ),
    ]
