# Generated by Django 4.2.19 on 2025-07-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('home', '0025_homepagehandball_homepagerugby_homepagetennis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagerugby',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
