# Generated by Django 4.2.19 on 2025-07-11 18:41

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homepagefootball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefootball',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_futsal', to='home.homepage'),
        ),
    ]
