# Generated by Django 4.2.19 on 2025-07-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        ('home', '0029_alter_homepagefootball_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageFootball',
            new_name='HomePageFutsal',
        ),
    ]
